const jjson=(data,init={})=>Response.json(data,{...init,headers:{'cache-control':'no-store',...(init.headers||{})}});
function cookieValue(r,n){for(const p of (r.headers.get('cookie')||'').split(';')){const[k,...v]=p.trim().split('=');if(k===n)return v.join('=')}return''}
async function token(secret,purpose){if(!secret)return'';const enc=new TextEncoder(),k=await crypto.subtle.importKey('raw',enc.encode(String(secret).trim()),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(purpose)));let b='';for(const x of sig)b+=String.fromCharCode(x);return btoa(b).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
async function adminAuthorized(r,e){const c=cookieValue(r,'bt_admin');return !!(c&&e.ADMIN_KEY&&c===await token(e.ADMIN_KEY,'bentoland-admin-session-v1'))}
async function familyAuthorized(r,e){const c=cookieValue(r,'bt_family');return !!(c&&e.FAMILY_KEY&&c===await token(e.FAMILY_KEY,'bentoland-family-session-v1'))}
function safeName(n='image'){return String(n).toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'image'}
function slugify(v='entry'){return String(v).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||`entry-${Date.now()}`}
function vis(v){return ['draft','private','public'].includes(v)?v:'draft'}
async function ensureJournalSchema(db){await db.prepare(`CREATE TABLE IF NOT EXISTS journal_entries (id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,subtitle TEXT NOT NULL DEFAULT '',body TEXT NOT NULL DEFAULT '',location TEXT NOT NULL DEFAULT '',entry_date TEXT NOT NULL DEFAULT '',camera TEXT NOT NULL DEFAULT '',lens TEXT NOT NULL DEFAULT '',visibility TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS journal_images (id INTEGER PRIMARY KEY AUTOINCREMENT,entry_id INTEGER NOT NULL,r2_key TEXT NOT NULL,filename TEXT NOT NULL DEFAULT '',caption TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();try{await db.prepare(`ALTER TABLE journal_images ADD COLUMN alt_text TEXT NOT NULL DEFAULT ''`).run()}catch{}await db.prepare('CREATE INDEX IF NOT EXISTS idx_journal_entries_visibility ON journal_entries(visibility,entry_date,created_at)').run();await db.prepare('CREATE INDEX IF NOT EXISTS idx_journal_images_entry ON journal_images(entry_id,sort_order,id)').run()}
async function hydrate(db,row){const{results}=await db.prepare('SELECT id,filename,caption,COALESCE(alt_text,\'\') alt_text,sort_order FROM journal_images WHERE entry_id=? ORDER BY sort_order ASC,id ASC').bind(row.id).all();const images=results.map(x=>({...x,url:`/journal-media/${x.id}`}));return{...row,images,cover:images[0]?.url||null}}
async function storeImages(e,entryId,slug,files){let order=0;for(const file of files){if(!(file instanceof File)||!file.size||!file.type.startsWith('image/'))continue;const key=`journal/${slug}/${Date.now()}-${crypto.randomUUID().slice(0,8)}-${safeName(file.name)}`;await e.PHOTOS.put(key,file.stream(),{httpMetadata:{contentType:file.type}});await e.DB.prepare('INSERT INTO journal_images (entry_id,r2_key,filename,sort_order) VALUES (?,?,?,?)').bind(entryId,key,file.name,order++).run()}}
function assetRequest(r,path){const u=new URL(r.url);u.pathname=path;u.search='';return new Request(u.toString(),{method:'GET',headers:r.headers})}
export async function handleJournalRequest(r,e){const u=new URL(r.url),p=u.pathname;const relevant=p==='/journal'||p==='/family'||p==='/admin/journal'||p.startsWith('/journal-api/')||p.startsWith('/journal-media/');if(!relevant)return null;if(p==='/journal')return e.ASSETS.fetch(assetRequest(r,'/journal.html'));if(p==='/family')return e.ASSETS.fetch(assetRequest(r,'/family.html'));if(p==='/admin/journal'){if(!await adminAuthorized(r,e))return new Response(null,{status:303,headers:{location:'/admin'}});return e.ASSETS.fetch(assetRequest(r,'/admin-journal.html'))}
if(p==='/journal-api/family/status'&&r.method==='GET')return jjson({family:await familyAuthorized(r,e),admin:await adminAuthorized(r,e)});
if(p==='/journal-api/family/login'&&r.method==='POST'){if(!e.FAMILY_KEY)return jjson({error:'Family access has not been configured yet.'},{status:503});const b=await r.json().catch(()=>({}));if(String(b.password||'')!==String(e.FAMILY_KEY))return jjson({error:'Wrong family password.'},{status:403});const t=await token(e.FAMILY_KEY,'bentoland-family-session-v1');return jjson({ok:true},{headers:{'set-cookie':`bt_family=${t}; Path=/; Max-Age=15552000; HttpOnly; Secure; SameSite=Lax`}})}
if(p==='/journal-api/family/logout'&&r.method==='POST')return jjson({ok:true},{headers:{'set-cookie':'bt_family=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax'}});
try{await ensureJournalSchema(e.DB)}catch(err){return jjson({error:'Journal database unavailable.',detail:String(err?.message||err)},{status:500})}
if(p==='/journal-api/entries'&&r.method==='GET'){const admin=await adminAuthorized(r,e),family=await familyAuthorized(r,e);let q;if(admin&&u.searchParams.get('all')==='1')q=e.DB.prepare("SELECT * FROM journal_entries ORDER BY COALESCE(NULLIF(entry_date,''),created_at) DESC,created_at DESC");else if(admin||family)q=e.DB.prepare("SELECT * FROM journal_entries WHERE visibility IN ('public','private') ORDER BY COALESCE(NULLIF(entry_date,''),created_at) DESC,created_at DESC");else q=e.DB.prepare("SELECT * FROM journal_entries WHERE visibility='public' ORDER BY COALESCE(NULLIF(entry_date,''),created_at) DESC,created_at DESC");const{results}=await q.all();return jjson({entries:await Promise.all(results.map(x=>hydrate(e.DB,x))),family,admin})}
const entryMatch=p.match(/^\/journal-api\/entries\/([^/]+)$/);if(entryMatch&&r.method==='GET'){const key=decodeURIComponent(entryMatch[1]);const row=/^\d+$/.test(key)?await e.DB.prepare('SELECT * FROM journal_entries WHERE id=?').bind(Number(key)).first():await e.DB.prepare('SELECT * FROM journal_entries WHERE slug=?').bind(key).first();if(!row)return jjson({error:'Entry not found.'},{status:404});const admin=await adminAuthorized(r,e),family=await familyAuthorized(r,e);if(row.visibility==='draft'&&!admin)return jjson({error:'Entry not found.'},{status:404});if(row.visibility==='private'&&!admin&&!family)return jjson({error:'Entry not found.'},{status:404});return jjson({entry:await hydrate(e.DB,row),family,admin})}
if(p==='/journal-api/admin/entries'&&r.method==='POST'){if(!await adminAuthorized(r,e))return jjson({error:'Unauthorized.'},{status:403});const f=await r.formData(),title=String(f.get('title')||'').trim();if(!title)return jjson({error:'Title is required.'},{status:400});const slug=`${slugify(title)}-${crypto.randomUUID().slice(0,8)}`,result=await e.DB.prepare('INSERT INTO journal_entries (slug,title,subtitle,body,location,entry_date,camera,lens,visibility) VALUES (?,?,?,?,?,?,?,?,?)').bind(slug,title,String(f.get('subtitle')||''),String(f.get('body')||''),String(f.get('location')||''),String(f.get('entry_date')||''),String(f.get('camera')||''),String(f.get('lens')||''),vis(String(f.get('visibility')||'draft'))).run(),id=Number(result.meta.last_row_id);await storeImages(e,id,slug,f.getAll('images'));return jjson({ok:true,id,slug})}
const adminEntry=p.match(/^\/journal-api\/admin\/entries\/(\d+)$/);if(adminEntry&&r.method==='PATCH'){if(!await adminAuthorized(r,e))return jjson({error:'Unauthorized.'},{status:403});const id=Number(adminEntry[1]),cur=await e.DB.prepare('SELECT * FROM journal_entries WHERE id=?').bind(id).first();if(!cur)return jjson({error:'Entry not found.'},{status:404});const b=await r.json().catch(()=>({})),v={title:Object.hasOwn(b,'title')?String(b.title||'').trim():cur.title,subtitle:Object.hasOwn(b,'subtitle')?String(b.subtitle||''):cur.subtitle,body:Object.hasOwn(b,'body')?String(b.body||''):cur.body,location:Object.hasOwn(b,'location')?String(b.location||''):cur.location,entry_date:Object.hasOwn(b,'entry_date')?String(b.entry_date||''):cur.entry_date,camera:Object.hasOwn(b,'camera')?String(b.camera||''):cur.camera,lens:Object.hasOwn(b,'lens')?String(b.lens||''):cur.lens,visibility:Object.hasOwn(b,'visibility')?vis(String(b.visibility)):cur.visibility};if(!v.title)return jjson({error:'Title is required.'},{status:400});await e.DB.prepare('UPDATE journal_entries SET title=?,subtitle=?,body=?,location=?,entry_date=?,camera=?,lens=?,visibility=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(v.title,v.subtitle,v.body,v.location,v.entry_date,v.camera,v.lens,v.visibility,id).run();return jjson({ok:true})}
if(adminEntry&&r.method==='DELETE'){if(!await adminAuthorized(r,e))return jjson({error:'Unauthorized.'},{status:403});const id=Number(adminEntry[1]),{results}=await e.DB.prepare('SELECT r2_key FROM journal_images WHERE entry_id=?').bind(id).all();for(const x of results)try{await e.PHOTOS.delete(x.r2_key)}catch{}await e.DB.prepare('DELETE FROM journal_images WHERE entry_id=?').bind(id).run();await e.DB.prepare('DELETE FROM journal_entries WHERE id=?').bind(id).run();return jjson({ok:true})}
const uploadMatch=p.match(/^\/journal-api\/admin\/entries\/(\d+)\/images$/);if(uploadMatch&&r.method==='POST'){if(!await adminAuthorized(r,e))return jjson({error:'Unauthorized.'},{status:403});const id=Number(uploadMatch[1]),row=await e.DB.prepare('SELECT slug FROM journal_entries WHERE id=?').bind(id).first();if(!row)return jjson({error:'Entry not found.'},{status:404});const f=await r.formData();await storeImages(e,id,row.slug,f.getAll('images'));await e.DB.prepare('UPDATE journal_entries SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();return jjson({ok:true})}
const imageMatch=p.match(/^\/journal-api\/admin\/images\/(\d+)$/);if(imageMatch&&r.method==='PATCH'){if(!await adminAuthorized(r,e))return jjson({error:'Unauthorized.'},{status:403});const id=Number(imageMatch[1]),row=await e.DB.prepare('SELECT id FROM journal_images WHERE id=?').bind(id).first();if(!row)return jjson({error:'Image not found.'},{status:404});const b=await r.json().catch(()=>({}));await e.DB.prepare('UPDATE journal_images SET caption=?,alt_text=? WHERE id=?').bind(String(b.caption||''),String(b.alt_text||''),id).run();return jjson({ok:true})}
if(imageMatch&&r.method==='DELETE'){if(!await adminAuthorized(r,e))return jjson({error:'Unauthorized.'},{status:403});const id=Number(imageMatch[1]),row=await e.DB.prepare('SELECT r2_key FROM journal_images WHERE id=?').bind(id).first();if(!row)return jjson({error:'Image not found.'},{status:404});try{await e.PHOTOS.delete(row.r2_key)}catch{}await e.DB.prepare('DELETE FROM journal_images WHERE id=?').bind(id).run();return jjson({ok:true})}
const media=p.match(/^\/journal-media\/(\d+)$/);if(media&&r.method==='GET'){const id=Number(media[1]),row=await e.DB.prepare('SELECT i.r2_key,e.visibility FROM journal_images i JOIN journal_entries e ON e.id=i.entry_id WHERE i.id=?').bind(id).first();if(!row)return new Response('Not found',{status:404});const admin=await adminAuthorized(r,e),family=await familyAuthorized(r,e);if(row.visibility==='draft'&&!admin)return new Response('Not found',{status:404});if(row.visibility==='private'&&!admin&&!family)return new Response('Not found',{status:404});const o=await e.PHOTOS.get(row.r2_key);if(!o)return new Response('Not found',{status:404});const h=new Headers();o.writeHttpMetadata(h);h.set('etag',o.httpEtag);h.set('cache-control',row.visibility==='public'?'public,max-age=86400':'private,no-store');return new Response(o.body,{headers:h})}return jjson({error:'Journal route not found.'},{status:404})}

// Runtime binding refresh: 2026-09-07
